trigger: 
  branches:
    include:
      - develop
    
    variables:
      -group: 'tpfinal-vars'

stages:
  - stage: Build
    displayName: 'Build stage'

jobs:
  - job: BuildFront
    displayName: 'Build Frontend'
    steps:
      - template: ./templates/_build-front.yml